# Generated by Django 5.0.4 on 2024-04-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='reviews_per_star',
        ),
    ]
